drop table if exists championnat 
drop table if exists client 
drop table if exists journee 
drop table if exists rencontre 

create table championnat (id bigint generated by default as identity, nb_equipes integer not null, nom varchar(255) not null, pays varchar(255) not null, saison varchar(255) not null, primary key (id))
create table club (id bigint generated by default as identity, date_creation date not null, nom varchar(255) not null, nom_president varchar(255) not null, nom_stade varchar(255) not null, pays varchar(255) not null, primary key (id))
Hibernate: create table journee (id bigint generated by default as identity, date date not null, championnat_id bigint, primary key (id))
Hibernate: create table rencontre (id bigint generated by default as identity, heure time not null, score_domicile integer not null, score_visiteur integer not null, journee_id bigint, primary key (id))

alter table client add constraint UK_edver7gtbfldp50jtkypbtr89 unique (nom)
alter table journee add constraint FK95fgbbonxnxo90k9dx8vmghrb foreign key (championnat_id) references championnat
alter table rencontre add constraint FKd3ki9996ol9vt82fgbbk98bwc foreign key (journee_id) references journee